### ISSUE TITLE
how to fix Entrypoint undefined?

### ISSUE THREAD

**Issue by byoungd** [lincenying/vue2-multiple-entry#13]
Console outputs some info like

` Entrypoint undefined = module2/index.html `

how to fix that?

Thanks!

**Comment by lincenying** [comment]
https://github.com/jantimon/html-webpack-plugin/issues/895

**Comment by byoungd** [comment]
So this is a common issue of HTMLWebpackPlugin with webpack4 and it doesn't affect anything right?

Thanks a lot!
