### ISSUE TITLE
dev后，访问异常

### ISSUE THREAD

**Issue by ruyangit** [lincenying/vue2-multiple-entry#15]
![a](https://user-images.githubusercontent.com/3294044/40901103-3b5f43ba-6801-11e8-9e43-e33265fc659f.png)

**Comment by ruyangit** [comment]
补充：dev启动后的提示
![b](https://user-images.githubusercontent.com/3294044/40901193-b1d34bae-6801-11e8-8dc8-2c21e03d613a.png)

**Comment by lincenying** [comment]
重新git pull下, 少打了个`$`
