### ISSUE TITLE
这种情况下，如何加个单页的代码分割功能

### ISSUE THREAD

**Issue by wbcz** [lincenying/vue2-multiple-entry#2]
我发现基于这个架构，做单页的代码分割好像不容易，不知道楼主有什么解决办法

**Comment by lincenying** [comment]
一般用路由了才需要分割代码, 把分割代码放在`modules/xxx/router/index.js`里就行了.

**Comment by lincenying** [comment]
https://github.com/lincenying/vue2-multiple-entry/blob/dev/src/modules/vuex/router/index.js#L4-L5

**Comment by wbcz** [comment]
const index = resolve => {
  require.ensure(['./../pages/index.vue'], () => {
    resolve(require('./../pages/index.vue'))
  })
}
const view = resolve => {
  require.ensure(['./../pages/view.vue'], () => {
    resolve(require('./../pages/view.vue'))
  })
}

用古老的写法怎么不行呢，难道webpack2不兼容？

**Comment by lincenying** [comment]
本仓库用的是webpack2, 请按上面发的链接里的写法写.
