### ISSUE TITLE
为什么我本地用express模拟数据的时候，总是报错呢

### ISSUE THREAD

**Issue by lily1115** [lincenying/vue2-multiple-entry#4]
![image](https://cloud.githubusercontent.com/assets/13074459/24182484/1338d95e-0efd-11e7-9f22-b34376b9464e.png)
![image](https://cloud.githubusercontent.com/assets/13074459/24182500/2e2f57ce-0efd-11e7-9ca8-d69a01af6f83.png)
![image](https://cloud.githubusercontent.com/assets/13074459/24182515/52f3a52e-0efd-11e7-942c-cdc9c9517c6b.png)
API文件里面index.js文件没有改动

**Comment by lily1115** [comment]
![image](https://cloud.githubusercontent.com/assets/13074459/24182547/8bd442a4-0efd-11e7-93d9-8bcab1d3b154.png)
你能写个本地模拟数据接口参考一下嘛

**Comment by lincenying** [comment]
第一张图   8080后面加个/
api: 'http://127.0.0.1:8080/'
