### ISSUE TITLE
template/index.html中的jquery在哪里有用到？

### ISSUE THREAD

**Issue by includeleec** [lincenying/vue2-multiple-entry#6]
template/index.html中的jquery在哪里有用到？
搜索了下代码，只是看到在webpack.base.conf.js里有用到，我注释掉，程序正常。
但是删除掉 <script src="//apps.bdimg.com/libs/jquery/2.1.4/jquery.min.js"></script>
页面就渲染不出来了。

**Comment by lincenying** [comment]
不需要jquery吧, 删除模版的cdn链接, 删除webpack.base.conf.js里的
```
externals: {
        'jquery': 'jQuery'
    },
```
和
```
new webpack.ProvidePlugin({$: 'jquery', jQuery: 'jquery', 'window.jQuery': 'jquery'}),
```

**Comment by includeleec** [comment]
嗯。我新建的module就这么做了，可以的，没问题。
但是原来你给的出的示例，
删掉  ` <script src="//apps.bdimg.com/libs/jquery/2.1.4/jquery.min.js"></script>` 就不行。

**Comment by lincenying** [comment]
toastr 插件需要用到 jquery
